// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: HWMV5

#ifndef _HWMV5_UI_H
#define _HWMV5_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen1.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_126065372);    // assets/Imagen de WhatsApp 2025-10-21 a las 20.35.33_ad477728 (1).png

// FONTS
LV_FONT_DECLARE(ui_font_Clock);
LV_FONT_DECLARE(ui_font_Font16_2);
LV_FONT_DECLARE(ui_font_Test);
LV_FONT_DECLARE(ui_font_Test16);
LV_FONT_DECLARE(ui_font_Test18);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
