// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: HWMV5

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_ArcCpu = NULL;
lv_obj_t * ui_TempCpuBar = NULL;
lv_obj_t * ui_TempGpuBar = NULL;
lv_obj_t * ui_Cpu = NULL;
lv_obj_t * ui_Gpu = NULL;
lv_obj_t * ui_cpuporc = NULL;
lv_obj_t * ui_gpuporc = NULL;
lv_obj_t * ui_fps = NULL;
lv_obj_t * ui_tempcpu = NULL;
lv_obj_t * ui_ArcGpu = NULL;
lv_obj_t * ui_tempgpu = NULL;
lv_obj_t * ui_FanCpu = NULL;
lv_obj_t * ui_FanCpu1 = NULL;
lv_obj_t * ui_Clock = NULL;
lv_obj_t * ui_RamUsage = NULL;
lv_obj_t * ui_VramUsage = NULL;
lv_obj_t * ui_FanCase = NULL;
lv_obj_t * ui_GpuClock = NULL;
lv_obj_t * ui_CPUW = NULL;
lv_obj_t * ui_GPUW1 = NULL;
// event funtions
void ui_event_TempCpuBar(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_bar_increment(ui_TempCpuBar, 1, LV_ANIM_ON);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Screen1, &ui_img_126065372, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcCpu = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_ArcCpu, 85);
    lv_obj_set_height(ui_ArcCpu, 85);
    lv_obj_set_x(ui_ArcCpu, -80);
    lv_obj_set_y(ui_ArcCpu, -50);
    lv_obj_set_align(ui_ArcCpu, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ArcCpu, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_arc_set_value(ui_ArcCpu, 50);
    ui_object_set_themeable_style_property(ui_ArcCpu, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR,
                                           _ui_theme_color_gray);
    ui_object_set_themeable_style_property(ui_ArcCpu, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_ARC_OPA,
                                           _ui_theme_alpha_gray);
    lv_obj_set_style_arc_width(ui_ArcCpu, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcCpu, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_ArcCpu, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcCpu, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_ArcCpu, 3, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ArcCpu, 3, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ArcCpu, 3, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ArcCpu, 3, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_TempCpuBar = lv_bar_create(ui_Screen1);
    lv_bar_set_mode(ui_TempCpuBar, LV_BAR_MODE_RANGE);
    lv_bar_set_value(ui_TempCpuBar, 50, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_TempCpuBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_TempCpuBar, 80);
    lv_obj_set_height(ui_TempCpuBar, 10);
    lv_obj_set_x(ui_TempCpuBar, -105);
    lv_obj_set_y(ui_TempCpuBar, -5);
    lv_obj_set_align(ui_TempCpuBar, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TempCpuBar, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_TempCpuBar, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_transform_angle(ui_TempCpuBar, -900, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempGpuBar = lv_bar_create(ui_Screen1);
    lv_bar_set_mode(ui_TempGpuBar, LV_BAR_MODE_RANGE);
    lv_bar_set_value(ui_TempGpuBar, 50, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_TempGpuBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_TempGpuBar, 80);
    lv_obj_set_height(ui_TempGpuBar, 10);
    lv_obj_set_x(ui_TempGpuBar, 175);
    lv_obj_set_y(ui_TempGpuBar, -5);
    lv_obj_set_align(ui_TempGpuBar, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TempGpuBar, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_TempGpuBar, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_transform_angle(ui_TempGpuBar, -900, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Cpu = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Cpu, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Cpu, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Cpu, -75);
    lv_obj_set_y(ui_Cpu, -105);
    lv_obj_set_align(ui_Cpu, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Cpu, "CPU");
    ui_object_set_themeable_style_property(ui_Cpu, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_CPUGPU);
    ui_object_set_themeable_style_property(ui_Cpu, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_CPUGPU);
    lv_obj_set_style_text_font(ui_Cpu, &ui_font_Test, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Gpu = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Gpu, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Gpu, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Gpu, 75);
    lv_obj_set_y(ui_Gpu, -105);
    lv_obj_set_align(ui_Gpu, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Gpu, "GPU");
    ui_object_set_themeable_style_property(ui_Gpu, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_CPUGPU);
    ui_object_set_themeable_style_property(ui_Gpu, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_CPUGPU);
    lv_obj_set_style_text_font(ui_Gpu, &ui_font_Test, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cpuporc = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_cpuporc, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cpuporc, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cpuporc, -80);
    lv_obj_set_y(ui_cpuporc, -50);
    lv_obj_set_align(ui_cpuporc, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cpuporc, "CPU%");
    ui_object_set_themeable_style_property(ui_cpuporc, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_CPUGPU);
    ui_object_set_themeable_style_property(ui_cpuporc, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_CPUGPU);
    lv_obj_set_style_text_font(ui_cpuporc, &ui_font_Test16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gpuporc = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_gpuporc, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gpuporc, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gpuporc, 80);
    lv_obj_set_y(ui_gpuporc, -50);
    lv_obj_set_align(ui_gpuporc, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gpuporc, "GPU%");
    ui_object_set_themeable_style_property(ui_gpuporc, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_CPUGPU);
    ui_object_set_themeable_style_property(ui_gpuporc, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_CPUGPU);
    lv_obj_set_style_text_font(ui_gpuporc, &ui_font_Test16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fps = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_fps, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fps, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_fps, 0);
    lv_obj_set_y(ui_fps, -90);
    lv_obj_set_align(ui_fps, LV_ALIGN_CENTER);
    lv_label_set_text(ui_fps, "FPS");
    lv_obj_clear_flag(ui_fps, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_fps, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Crit);
    ui_object_set_themeable_style_property(ui_fps, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Crit);
    lv_obj_set_style_text_font(ui_fps, &ui_font_Test, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempcpu = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_tempcpu, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempcpu, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempcpu, -129);
    lv_obj_set_y(ui_tempcpu, -104);
    lv_obj_set_align(ui_tempcpu, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempcpu, "°C");
    lv_obj_clear_flag(ui_tempcpu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_tempcpu, &ui_font_Font16_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcGpu = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_ArcGpu, 85);
    lv_obj_set_height(ui_ArcGpu, 85);
    lv_obj_set_x(ui_ArcGpu, 80);
    lv_obj_set_y(ui_ArcGpu, -50);
    lv_obj_set_align(ui_ArcGpu, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ArcGpu, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_arc_set_value(ui_ArcGpu, 50);
    ui_object_set_themeable_style_property(ui_ArcGpu, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR,
                                           _ui_theme_color_gray);
    ui_object_set_themeable_style_property(ui_ArcGpu, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_ARC_OPA,
                                           _ui_theme_alpha_gray);
    lv_obj_set_style_arc_width(ui_ArcGpu, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcGpu, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_ArcGpu, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcGpu, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_ArcGpu, 3, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ArcGpu, 3, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ArcGpu, 3, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ArcGpu, 3, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_tempgpu = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_tempgpu, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempgpu, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempgpu, 129);
    lv_obj_set_y(ui_tempgpu, -104);
    lv_obj_set_align(ui_tempgpu, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempgpu, "°C");
    lv_obj_clear_flag(ui_tempgpu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_tempgpu, &ui_font_Font16_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FanCpu = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_FanCpu, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FanCpu, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FanCpu, -80);
    lv_obj_set_y(ui_FanCpu, 25);
    lv_obj_set_align(ui_FanCpu, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FanCpu, "RpmCpu");
    lv_obj_clear_flag(ui_FanCpu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_FanCpu, lv_color_hex(0xFF9200), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FanCpu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FanCpu, &ui_font_Font16_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FanCpu1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_FanCpu1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FanCpu1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FanCpu1, 80);
    lv_obj_set_y(ui_FanCpu1, 25);
    lv_obj_set_align(ui_FanCpu1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FanCpu1, "RpmGpu");
    lv_obj_clear_flag(ui_FanCpu1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_FanCpu1, lv_color_hex(0xFF9200), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FanCpu1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FanCpu1, &ui_font_Font16_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Clock = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Clock, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Clock, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Clock, 80);
    lv_obj_set_y(ui_Clock, 90);
    lv_obj_set_align(ui_Clock, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Clock, "HS:MI");
    lv_obj_set_style_text_color(ui_Clock, lv_color_hex(0x0F00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Clock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Clock, &ui_font_Clock, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RamUsage = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_RamUsage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RamUsage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RamUsage, -85);
    lv_obj_set_y(ui_RamUsage, 50);
    lv_obj_set_align(ui_RamUsage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RamUsage, "Ram: #### mb");
    lv_obj_set_style_text_color(ui_RamUsage, lv_color_hex(0x00FF86), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RamUsage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RamUsage, &ui_font_Font16_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VramUsage = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_VramUsage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VramUsage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VramUsage, -80);
    lv_obj_set_y(ui_VramUsage, 75);
    lv_obj_set_align(ui_VramUsage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VramUsage, "VRam: #### mb");
    lv_obj_set_style_text_color(ui_VramUsage, lv_color_hex(0x00FF86), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VramUsage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VramUsage, &ui_font_Font16_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FanCase = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_FanCase, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FanCase, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FanCase, -80);
    lv_obj_set_y(ui_FanCase, 100);
    lv_obj_set_align(ui_FanCase, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FanCase, "Case: #### RPM");
    lv_obj_clear_flag(ui_FanCase, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_FanCase, lv_color_hex(0xFF9200), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FanCase, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FanCase, &ui_font_Font16_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GpuClock = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_GpuClock, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GpuClock, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GpuClock, 80);
    lv_obj_set_y(ui_GpuClock, 50);
    lv_obj_set_align(ui_GpuClock, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GpuClock, "Clock: #### MHz");
    lv_obj_clear_flag(ui_GpuClock, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_GpuClock, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Crit);
    ui_object_set_themeable_style_property(ui_GpuClock, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Crit);
    lv_obj_set_style_text_font(ui_GpuClock, &ui_font_Font16_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CPUW = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_CPUW, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CPUW, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CPUW, -80);
    lv_obj_set_y(ui_CPUW, 1);
    lv_obj_set_align(ui_CPUW, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CPUW, "CPU W");
    lv_obj_clear_flag(ui_CPUW, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_CPUW, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_CPUGPU);
    ui_object_set_themeable_style_property(ui_CPUW, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_CPUGPU);
    lv_obj_set_style_text_font(ui_CPUW, &ui_font_Font16_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GPUW1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_GPUW1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GPUW1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GPUW1, 80);
    lv_obj_set_y(ui_GPUW1, 1);
    lv_obj_set_align(ui_GPUW1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GPUW1, "GPU W");
    lv_obj_clear_flag(ui_GPUW1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_GPUW1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_CPUGPU);
    ui_object_set_themeable_style_property(ui_GPUW1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_CPUGPU);
    lv_obj_set_style_text_font(ui_GPUW1, &ui_font_Font16_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_TempCpuBar, ui_event_TempCpuBar, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_ArcCpu = NULL;
    ui_TempCpuBar = NULL;
    ui_TempGpuBar = NULL;
    ui_Cpu = NULL;
    ui_Gpu = NULL;
    ui_cpuporc = NULL;
    ui_gpuporc = NULL;
    ui_fps = NULL;
    ui_tempcpu = NULL;
    ui_ArcGpu = NULL;
    ui_tempgpu = NULL;
    ui_FanCpu = NULL;
    ui_FanCpu1 = NULL;
    ui_Clock = NULL;
    ui_RamUsage = NULL;
    ui_VramUsage = NULL;
    ui_FanCase = NULL;
    ui_GpuClock = NULL;
    ui_CPUW = NULL;
    ui_GPUW1 = NULL;

}
