// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: HWMV5

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_ArcCpu;
extern void ui_event_TempCpuBar(lv_event_t * e);
extern lv_obj_t * ui_TempCpuBar;
extern lv_obj_t * ui_TempGpuBar;
extern lv_obj_t * ui_Cpu;
extern lv_obj_t * ui_Gpu;
extern lv_obj_t * ui_cpuporc;
extern lv_obj_t * ui_gpuporc;
extern lv_obj_t * ui_fps;
extern lv_obj_t * ui_tempcpu;
extern lv_obj_t * ui_ArcGpu;
extern lv_obj_t * ui_tempgpu;
extern lv_obj_t * ui_FanCpu;
extern lv_obj_t * ui_FanCpu1;
extern lv_obj_t * ui_Clock;
extern lv_obj_t * ui_RamUsage;
extern lv_obj_t * ui_VramUsage;
extern lv_obj_t * ui_FanCase;
extern lv_obj_t * ui_GpuClock;
extern lv_obj_t * ui_CPUW;
extern lv_obj_t * ui_GPUW1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

