// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: HWMV5

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_CPUGPU[1] = {0x00A0FF};
const ui_theme_variable_t _ui_theme_alpha_CPUGPU[1] = {255};

const ui_theme_variable_t _ui_theme_color_Text[1] = {0x00FF17};
const ui_theme_variable_t _ui_theme_alpha_Text[1] = {255};

const ui_theme_variable_t _ui_theme_color_Warn[1] = {0xFF7D00};
const ui_theme_variable_t _ui_theme_alpha_Warn[1] = {255};

const ui_theme_variable_t _ui_theme_color_Crit[1] = {0xFF0000};
const ui_theme_variable_t _ui_theme_alpha_Crit[1] = {255};

const ui_theme_variable_t _ui_theme_color_gray[1] = {0x515151};
const ui_theme_variable_t _ui_theme_alpha_gray[1] = {255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

